name: E2E - Keycloak v24

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'packages/core/**'
      - 'e2e/providers/keycloak/**'
      - 'e2e/providers/shared-tests.ts'
      - 'e2e/providers/types.ts'
  pull_request:
    branches: [main]
    paths:
      - 'packages/core/**'
      - 'e2e/providers/keycloak/**'
      - 'e2e/providers/shared-tests.ts'
      - 'e2e/providers/types.ts'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    uses: ./.github/workflows/e2e-provider.yml
    with:
      provider: keycloak
      version: v24
      port: '8024'
      image: quay.io/keycloak/keycloak:24.0.5
